IMG_NAME='minebox-pi5'
PI_GEN_RELEASE='MineBox OS'
RELEASE='trixie'
DEPLOY_COMPRESSION='xz'
LOCALE_DEFAULT='en_US.UTF-8'
KEYBOARD_KEYMAP='us'
KEYBOARD_LAYOUT='English (US)'
TIMEZONE_DEFAULT='America/Chicago'
FIRST_USER_NAME='minebox'
FIRST_USER_PASS='minebox'
DISABLE_FIRST_BOOT_USER_RENAME=1
PASSWORDLESS_SUDO=0
ENABLE_SSH=1
ENABLE_CLOUD_INIT=0
WPA_COUNTRY='US'
TARGET_HOSTNAME='minebox'
STAGE_LIST='stage0 stage1 stage2 stage-minebox'
