interface=wlan0
bind-dynamic
dhcp-range=192.168.4.10,192.168.4.254,255.255.255.0,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
domain-needed
bogus-priv
address=/msftconnecttest.com/192.168.4.1
address=/www.msftconnecttest.com/192.168.4.1
address=/msftncsi.com/192.168.4.1
address=/www.msftncsi.com/192.168.4.1
address=/dns.msftncsi.com/192.168.4.1
address=/connectivitycheck.gstatic.com/192.168.4.1
address=/clients3.google.com/192.168.4.1
address=/captive.apple.com/192.168.4.1
address=/www.apple.com/192.168.4.1
address=/minebox.local/192.168.4.1
address=/minebox/192.168.4.1
