"""Hardware HAL protocol / base class."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from hardware.types import FanState, FeatureStatus, HardwareHealth, InputEvent


@runtime_checkable
class HardwareProfile(Protocol):
    profile_name: str

    def read_left_button(self) -> bool: ...
    def read_right_button(self) -> bool: ...
    def read_encoder_delta(self) -> int: ...
    def read_encoder_press(self) -> bool: ...
    def set_left_led(self, on: bool) -> FeatureStatus: ...
    def set_right_led(self, on: bool) -> FeatureStatus: ...
    def read_cpu_temperature_c(self) -> float | None: ...
    def set_fan(self, state: FanState) -> FeatureStatus: ...
    def get_fan_state(self) -> FanState: ...
    def read_throttling_state(self) -> str: ...
    def request_shutdown(self) -> FeatureStatus: ...
    def request_reboot(self) -> FeatureStatus: ...
    def health(self) -> HardwareHealth: ...
    def capabilities(self) -> dict[str, str]: ...
    def diagnostic_snapshot(self) -> dict: ...
    def pop_events(self) -> list[InputEvent]: ...
    def close(self) -> None: ...
