motd=Server
server-port=25565
enable-query=false
enable-rcon=true
rcon.port=25575
rcon.password=nefcEjCoV9Ajgw0Geo67VRMvepZTMsKN
broadcast-rcon-to-ops=true
online-mode=true
difficulty=easy
gamemode=survival
max-players=20
view-distance=10
simulation-distance=10
