"""nftables policy generation and static validation (Checkpoint 6)."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

from networking.roles import validate_iface_name

HOTSPOT_SUBNET = "192.168.4.0/24"
HOTSPOT_ADDR = "192.168.4.1"

# Minecraft default; overridable via env for tests.
MINECRAFT_PORT = int(os.environ.get("MINEBOX_MINECRAFT_PORT", "25565"))
DASHBOARD_PORT = int(os.environ.get("MINEBOX_DASHBOARD_PORT", "8080"))
# Simple Voice Chat (and similar proximity-chat mods) use UDP, not TCP 25565.
VOICECHAT_PORT = int(os.environ.get("MINEBOX_VOICECHAT_PORT", "24454"))


def generate_nftables(
    *,
    hotspot_iface: str,
    internet_sharing: bool,
    lan_dashboard: bool = True,
    lan_minecraft: bool = True,
    allow_ssh_on_hotspot: bool = False,
    allow_ssh_on_lan: bool = False,
) -> str:
    """Generate a default-deny-oriented inet filter + optional NAT ruleset."""
    hs = validate_iface_name(hotspot_iface) or "wlan0"
    mc = MINECRAFT_PORT
    dash = DASHBOARD_PORT
    vc = VOICECHAT_PORT

    ssh_hotspot = "tcp dport 22 accept" if allow_ssh_on_hotspot else ""
    # WAN: never accept dashboard/SSH/RCON from non-hotspot/non-lan in this base policy.
    # LAN access uses iif != hotspot and != lo with optional accepts.

    lan_rules = []
    if lan_dashboard:
        lan_rules.append(
            f'        iifname != "{hs}" iifname != "lo" iifname != "tailscale0" '
            f"tcp dport {{ 80, {dash} }} accept"
        )
    if lan_minecraft:
        lan_rules.append(
            f'        iifname != "{hs}" iifname != "lo" iifname != "tailscale0" '
            f"tcp dport {mc} accept"
        )
        lan_rules.append(
            f'        iifname != "{hs}" iifname != "lo" iifname != "tailscale0" '
            f"udp dport {vc} accept"
        )
    if allow_ssh_on_lan:
        lan_rules.append(
            f'        iifname != "{hs}" iifname != "lo" iifname != "tailscale0" '
            "tcp dport 22 accept"
        )
    lan_block = "\n".join(lan_rules)

    forward_sharing = ""
    nat_sharing = ""
    if internet_sharing:
        forward_sharing = f"""
        # Optional internet sharing (hotspot clients → uplink only).
        iifname "{hs}" oifname != "{hs}" ip saddr {HOTSPOT_SUBNET} accept
        iifname != "{hs}" oifname "{hs}" ip daddr {HOTSPOT_SUBNET} ct state established,related accept
"""
        nat_sharing = f"""
table ip minebox_nat {{
    chain postrouting {{
        type nat hook postrouting priority 100; policy accept;
        ip saddr {HOTSPOT_SUBNET} oifname != "{hs}" masquerade
    }}
}}
"""

    ssh_line = f'        iifname "{hs}" {ssh_hotspot}\n' if ssh_hotspot else ""

    return f"""#!/usr/sbin/nft -f
# Generated by MineBox networking.firewall — do not hand-edit on appliance;
# regenerate via minebox network policy apply.

flush ruleset

table inet minebox_filter {{
    chain input {{
        type filter hook input priority 0; policy drop;

        iifname "lo" accept
        ct state established,related accept
        ct state invalid drop

        # ICMP (limited) for local diagnostics
        ip protocol icmp icmp type echo-request limit rate 5/second accept

        # mDNS so home-LAN clients can resolve minebox.local
        ip protocol igmp accept
        udp dport 5353 accept

        # Hotspot: DHCP, DNS, dashboard, Minecraft, voice chat (and optional SSH)
        iifname "{hs}" udp dport {{ 53, 67, {vc} }} accept
        iifname "{hs}" tcp dport {{ 53, 80, {dash}, {mc} }} accept
{ssh_line}
        # Tailscale interface — only when present; exposure toggles are app-level.
        iifname "tailscale0" tcp dport {{ 80, {dash}, {mc} }} accept
        iifname "tailscale0" udp dport {vc} accept

{lan_block}

        # Explicitly drop management from unknown/WAN paths (RCON never open).
        tcp dport {{ 25575, 22 }} drop
        tcp dport {{ 80, {dash} }} drop
    }}

    chain forward {{
        type filter hook forward priority 0; policy drop;
        ct state established,related accept
        ct state invalid drop
{forward_sharing}
    }}
}}

{nat_sharing}
"""


def validate_nftables_text(text: str) -> dict[str, Any]:
    """Static validation suitable for CI (no root / nft binary required)."""
    errors: list[str] = []
    warnings: list[str] = []

    if "flush ruleset" not in text:
        errors.append("missing flush ruleset")
    if "policy drop" not in text:
        errors.append("input/forward should be default-drop oriented")
    if "25575" not in text and "rcon" not in text.lower():
        warnings.append("RCON port 25575 not mentioned — ensure it stays closed")
    if "masquerade" in text and HOTSPOT_SUBNET not in text:
        errors.append("NAT masquerade without hotspot subnet")
    if re.search(r"iifname\s+\"wlan1\".*dport.*8080", text) and "policy drop" in text:
        pass
    # Reject shell-injection markers (nft statements may end with ';').
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or not stripped:
            continue
        if any(tok in stripped for tok in ("`", "$(", "${", " && ", " || ", "| bash", "| sh")):
            errors.append(f"suspicious token in rule: {stripped[:80]}")

    if 'iifname "lo" accept' not in text and "iif lo" not in text:
        errors.append("loopback accept missing")

    return {
        "ok": not errors,
        "errors": errors,
        "warnings": warnings,
        "has_nat": "masquerade" in text,
        "default_drop": "policy drop" in text,
    }


def write_nftables_file(text: str, path: Path | None = None) -> Path:
    target = path or Path(os.environ.get("MINEBOX_NFT_FILE", "/etc/nftables.conf"))
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(target)
    return target


def internet_sharing_enabled() -> bool:
    try:
        from core.minebox_config import get_config

        return bool(get_config().internet_sharing)
    except Exception:
        return os.environ.get("MINEBOX_INTERNET_SHARING", "0").strip().lower() in {
            "1",
            "true",
            "yes",
            "on",
        }


def build_policy_for_roles(hotspot_iface: str | None, *, has_uplink: bool) -> dict[str, Any]:
    sharing = internet_sharing_enabled() and has_uplink and bool(hotspot_iface)
    # SoftAP bring-up SSH stays on hotspot. Home LAN also allows SSH so the
    # appliance can be administered without joining MineBox-Setup.
    text = generate_nftables(
        hotspot_iface=hotspot_iface or "wlan0",
        internet_sharing=sharing,
        allow_ssh_on_hotspot=True,
        allow_ssh_on_lan=True,
    )
    check = validate_nftables_text(text)
    return {
        "internet_sharing_active": sharing,
        "internet_sharing_configured": internet_sharing_enabled(),
        "hotspot_iface": hotspot_iface,
        "ruleset": text,
        "validation": check,
    }
