#Minecraft server properties
#Fri Jul 24 13:16:17 CDT 2026
allow-flight=false
broadcast-rcon-to-ops=true
difficulty=1
enable-query=false
enable-rcon=true
force-gamemode=false
gamemode=0
generate-structures=true
max-players=20
motd=My MineBox Server
online-mode=true
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
rcon.password=Aba2lXV9RAyFQThiS7zyPlLjUNf9e7vb
rcon.port=25575
resource-pack=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-npcs=true
use-native-transport=true
view-distance=10
